services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
      - redis

  horizon:
      build:
          context: .
          dockerfile: docker/Dockerfile
      volumes:
          - .:/var/www/html
          - /home/ubuntu/Documents/server1/exports:/var/www/html/exports
      depends_on:
          - db
          - redis
      command: ["php", "artisan", "horizon"]

  redis:
      image: redis:7.0-alpine
      platform: linux/amd64
      ports:
          - "6379:6379"
      command: redis-server --requirepass ${REDIS_PASSWORD}

  scheduler:
      build:
          context: .
          dockerfile: docker/Dockerfile
      volumes:
          - .:/var/www/html
      depends_on:
          - db
          - redis
      command: ["php", "artisan", "schedule:work"]

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    env_file:
      - .env

volumes:
  db_data:
