name: Deploy to Server

on:
  workflow_dispatch:  # Déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy and Configure Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Démarrage de la copie des fichiers avec rsync..."
            rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git' . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.APP_PATH }}
            echo "Copie terminée. Mise à jour de la configuration Nginx..."
            cp ${{ secrets.APP_PATH }}/nginx.prod.conf /etc/nginx/nginx.conf
            sudo systemctl restart nginx
            cd ${{ secrets.APP_PATH }}
            docker-compose down
            docker-compose up -d --build
